### ISSUE TITLE
code release time?

### ISSUE THREAD

**Issue by yun97** [ChenRocks/Distill-BERT-Textgen#1]
Could you please release the code? There is only readme.md.......

**Comment by ych133** [comment]
In one or two weeks.

**Comment by ych133** [comment]
> Could you please release the code? There is only readme.md.......

probably in two weeks.

**Comment by ChenRocks** [comment]
Thank you for your interest. We are working with company legal team to get opensource approval. This process should take no more than two weeks. I will try my best to push it forward.

**Comment by ChenRocks** [comment]
We have released the code. Thanks again for your interest.

**Comment by lemon234071** [comment]
> We have released the code. Thanks again for your interest.

Nice!!! Thank you.
