### ISSUE TITLE
About the vocabulary alignment

### ISSUE THREAD

**Issue by kugwzk** [ChenRocks/Distill-BERT-Textgen#3]
Thanks for your interesting work~
I have some curiosity about how you alignment the BERT MLM output vocabulary distribution with the Seq2seq output? Is the vocabulary same in the models?

**Comment by lemon234071** [comment]
I also curiosity about this problem. If two models have the same vocabulary, the output is BPE style? so every token in the vocabulary dose not indicate a complete word?

**Comment by ChenRocks** [comment]
I used the BPE vocabulary from [multilingual BERT (cased)](https://github.com/google-research/bert/blob/master/multilingual.md) to tokenize both the source and target sentence for MT tasks. Therefore, vocabulary is the same for both teacher and student.

**Comment by ChenRocks** [comment]
Closing this since no further discussion (code has been released).
